<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            ['name' => 'Yokohama ADVAN A052 Performance Tire', 'currentInventory' => 48, 'avgSalesPerWeek' => 8, 'leadTimeDays' => 6],
            ['name' => 'Brembo GT Series Brake Pads', 'currentInventory' => 30, 'avgSalesPerWeek' => 4, 'leadTimeDays' => 7],
            ['name' => 'Toyo Proxes R888R Racing Tire', 'currentInventory' => 36, 'avgSalesPerWeek' => 8, 'leadTimeDays' => 7],
            ['name' => 'Bosch Platinum Spark Plug', 'currentInventory' => 120, 'avgSalesPerWeek' => 25, 'leadTimeDays' => 5],
            ['name' => 'Michelin Pilot Sport 4S Tire', 'currentInventory' => 38, 'avgSalesPerWeek' => 4, 'leadTimeDays' => 5],
            ['name' => 'Pirelli P Zero High-Performance Tire', 'currentInventory' => 32, 'avgSalesPerWeek' => 2, 'leadTimeDays' => 6],
            ['name' => 'Continental ExtremeContact Sport Tire', 'currentInventory' => 40, 'avgSalesPerWeek' => 6, 'leadTimeDays' => 5],
            ['name' => 'Brembo Front Brake Rotors', 'currentInventory' => 28, 'avgSalesPerWeek' => 9, 'leadTimeDays' => 7],
            ['name' => 'Bosch Air Filter', 'currentInventory' => 90, 'avgSalesPerWeek' => 20, 'leadTimeDays' => 4],
            ['name' => 'Denso Iridium Spark Plug', 'currentInventory' => 110, 'avgSalesPerWeek' => 22, 'leadTimeDays' => 5],
            ['name' => 'Goodyear Eagle F1 Asymmetric Tire', 'currentInventory' => 41, 'avgSalesPerWeek' => 5, 'leadTimeDays' => 4],
            ['name' => 'Hankook Ventus S1 Evo3 Tire', 'currentInventory' => 53, 'avgSalesPerWeek' => 11, 'leadTimeDays' => 5],
            ['name' => 'Brembo Rear Brake Pads', 'currentInventory' => 26, 'avgSalesPerWeek' => 8, 'leadTimeDays' => 6],
            ['name' => 'Mann Oil Filter', 'currentInventory' => 100, 'avgSalesPerWeek' => 24, 'leadTimeDays' => 4],
            ['name' => 'Bosch Wiper Blade', 'currentInventory' => 85, 'avgSalesPerWeek' => 18, 'leadTimeDays' => 3],
            ['name' => 'AC Delco Battery', 'currentInventory' => 55, 'avgSalesPerWeek' => 15, 'leadTimeDays' => 5],
            ['name' => 'Yokohama BluEarth AE50 Tire', 'currentInventory' => 43, 'avgSalesPerWeek' => 11, 'leadTimeDays' => 7],
            ['name' => 'Toyo Open Country A/T III Tire', 'currentInventory' => 37, 'avgSalesPerWeek' => 10, 'leadTimeDays' => 6],
            ['name' => 'Brembo Brake Fluid', 'currentInventory' => 60, 'avgSalesPerWeek' => 16, 'leadTimeDays' => 4],
            ['name' => 'Bosch Oxygen Sensor', 'currentInventory' => 70, 'avgSalesPerWeek' => 14, 'leadTimeDays' => 6],
            ['name' => 'Yokohama BluEarth-Es ES32', 'currentInventory' => 28, 'avgSalesPerWeek' => 14, 'leadTimeDays' => 7],
            ['name' => 'Yokohama ADVAN Sport V105 Tire', 'currentInventory' => 32, 'avgSalesPerWeek' => 10, 'leadTimeDays' => 7],
            ['name' => 'HKS Hipermax S Suspension', 'currentInventory' => 15, 'avgSalesPerWeek' => 6, 'leadTimeDays' => 4],
            ['name' => 'TOMICA 55th Anniversary Edition Honda CIVIC TYPE R', 'currentInventory' => 20, 'avgSalesPerWeek' => 5, 'leadTimeDays' => 5],
            ['name' => 'NISMO Tshirt White', 'currentInventory' => 50, 'avgSalesPerWeek' => 15, 'leadTimeDays' => 3],
            ['name' => 'Brembo Prime Ceramic Brake Pads', 'currentInventory' => 30, 'avgSalesPerWeek' => 9, 'leadTimeDays' => 7],
            ['name' => 'Bride Zeta IV Racing Seat', 'currentInventory' => 20, 'avgSalesPerWeek' => 3, 'leadTimeDays' => 9],
            ['name' => 'Mini GT Porsche 911 Carrera RS 2.7', 'currentInventory' => 14, 'avgSalesPerWeek' => 5, 'leadTimeDays' => 3],
            ['name' => 'Hot Wheels Premium Nissan Skyline GT-R', 'currentInventory' => 16, 'avgSalesPerWeek' => 3, 'leadTimeDays' => 2],
            ['name' => 'Arai RX-7V Helmet', 'currentInventory' => 18, 'avgSalesPerWeek' => 6, 'leadTimeDays' => 8],
            ['name' => 'Shoei GT-Air II Helmet', 'currentInventory' => 20, 'avgSalesPerWeek' => 8, 'leadTimeDays' => 7],
            ['name' => 'AGV K6 Helmet', 'currentInventory' => 22, 'avgSalesPerWeek' => 9, 'leadTimeDays' => 9],
            ['name' => 'Alpinestars GP Pro Gloves', 'currentInventory' => 35, 'avgSalesPerWeek' => 13, 'leadTimeDays' => 6],
            ['name' => 'Dainese Racing 3 Jacket', 'currentInventory' => 25, 'avgSalesPerWeek' => 10, 'leadTimeDays' => 7],
            ['name' => 'Revit Sand 4 Pants', 'currentInventory' => 30, 'avgSalesPerWeek' => 12, 'leadTimeDays' => 6],
            ['name' => 'Yoshimura R-11 Exhaust', 'currentInventory' => 12, 'avgSalesPerWeek' => 5, 'leadTimeDays' => 8],
            ['name' => 'Brembo Racing Brake Kit', 'currentInventory' => 10, 'avgSalesPerWeek' => 4, 'leadTimeDays' => 9],
            ['name' => 'Ohlins Rear Shock Absorber', 'currentInventory' => 16, 'avgSalesPerWeek' => 4, 'leadTimeDays' => 7],
            ['name' => 'Pirelli Diablo Supercorsa Tires', 'currentInventory' => 30, 'avgSalesPerWeek' => 8, 'leadTimeDays' => 7],
            ['name' => 'Bridgestone Battlax Hypersport Tires', 'currentInventory' => 28, 'avgSalesPerWeek' => 6, 'leadTimeDays' => 7],
            ['name' => 'GoPro Hero 12 Mount Kit', 'currentInventory' => 50, 'avgSalesPerWeek' => 18, 'leadTimeDays' => 5],
            ['name' => 'Oxford Tank Bag', 'currentInventory' => 40, 'avgSalesPerWeek' => 15, 'leadTimeDays' => 6],
            ['name' => 'Racing Keychain Lanyard', 'currentInventory' => 100, 'avgSalesPerWeek' => 30, 'leadTimeDays' => 3],
            ['name' => 'Tire Pressure Gauge', 'currentInventory' => 65, 'avgSalesPerWeek' => 12, 'leadTimeDays' => 4],
            ['name' => 'LED Headlight Kit', 'currentInventory' => 65, 'avgSalesPerWeek' => 20, 'leadTimeDays' => 5],
            ['name' => 'Chain Cleaning Brush Set', 'currentInventory' => 80, 'avgSalesPerWeek' => 28, 'leadTimeDays' => 3],
            ['name' => 'Motorcycle Stand (Rear Paddock)', 'currentInventory' => 35, 'avgSalesPerWeek' => 12, 'leadTimeDays' => 9],
            ['name' => 'Riding Backpack (Hydration Ready)', 'currentInventory' => 60, 'avgSalesPerWeek' => 22, 'leadTimeDays' => 6],
            ['name' => 'Maisto 1:24 Diecast Ford Mustang GT', 'currentInventory' => 10, 'avgSalesPerWeek' => 3, 'leadTimeDays' => 3],
            ['name' => 'Maisto 1:24 Diecast Dodge Charger', 'currentInventory' => 10, 'avgSalesPerWeek' => 2, 'leadTimeDays' => 4],
            ['name' => 'Greenlight 1:64 Dodge Ram 1500', 'currentInventory' => 15, 'avgSalesPerWeek' => 4, 'leadTimeDays' => 5],
            ['name' => 'AUTOart 1:18 Porsche 911 Turbo S', 'currentInventory' => 6, 'avgSalesPerWeek' => 1, 'leadTimeDays' => 12],
            ['name' => 'Bburago 1:24 Lamborghini Huracan Spyder', 'currentInventory' => 10, 'avgSalesPerWeek' => 5, 'leadTimeDays' => 7],
            ['name' => 'Jada Toys 1:24 Tesla Model S', 'currentInventory' => 10, 'avgSalesPerWeek' => 2, 'leadTimeDays' => 5],
            ['name' => 'Schuco 1:43 Mercedes-Benz 300SL', 'currentInventory' => 3, 'avgSalesPerWeek' => 1, 'leadTimeDays' => 8],
            ['name' => 'Tarmac Works 1:64 Nissan Skyline GT-R R32', 'currentInventory' => 15, 'avgSalesPerWeek' => 8, 'leadTimeDays' => 5],
            ['name' => 'Kyosho 1:18 Ferrari F40', 'currentInventory' => 7, 'avgSalesPerWeek' => 2, 'leadTimeDays' => 10],
            ['name' => 'Welly 1:24 BMW M3 E30', 'currentInventory' => 7, 'avgSalesPerWeek' => 2, 'leadTimeDays' => 6],
            ['name' => 'Motul Fully Synthetic Brake Fluid', 'currentInventory' => 100, 'avgSalesPerWeek' => 35, 'leadTimeDays' => 4],
            ['name' => 'K&N High Performance Air Filter', 'currentInventory' => 80, 'avgSalesPerWeek' => 30, 'leadTimeDays' => 5],
            ['name' => 'Thule Roof Rack System', 'currentInventory' => 40, 'avgSalesPerWeek' => 15, 'leadTimeDays' => 7],
            ['name' => 'Blaupunkt Car Audio System', 'currentInventory' => 35, 'avgSalesPerWeek' => 12, 'leadTimeDays' => 9],
            ['name' => 'Anker Roav SmartCharge F2 Dash Cam', 'currentInventory' => 65, 'avgSalesPerWeek' => 20, 'leadTimeDays' => 5],
            ['name' => 'WeatherTech All-Weather Floor Mats', 'currentInventory' => 120, 'avgSalesPerWeek' => 40, 'leadTimeDays' => 2],
            ['name' => 'Bosal Exhaust System', 'currentInventory' => 25, 'avgSalesPerWeek' => 8, 'leadTimeDays' => 14],
            ['name' => 'Garmin DriveSmart 65 GPS Navigator', 'currentInventory' => 50, 'avgSalesPerWeek' => 12, 'leadTimeDays' => 4],
            ['name' => 'Michelin Defender T+H Tire', 'currentInventory' => 48, 'avgSalesPerWeek' => 6, 'leadTimeDays' => 7],
            ['name' => 'Rain-X Latitude Water Repellency Wiper Blades', 'currentInventory' => 75, 'avgSalesPerWeek' => 28, 'leadTimeDays' => 3],
            ['name' => 'K&N Performance Oil Filter', 'currentInventory' => 108, 'avgSalesPerWeek' => 30, 'leadTimeDays' => 5],
            ['name' => 'Thule Cargo Box', 'currentInventory' => 20, 'avgSalesPerWeek' => 7, 'leadTimeDays' => 12],
            ['name' => 'Pioneer AVH-W4500NEX Multimedia Receiver', 'currentInventory' => 35, 'avgSalesPerWeek' => 14, 'leadTimeDays' => 8],
            ['name' => 'Bosch 24V Truck Battery', 'currentInventory' => 40, 'avgSalesPerWeek' => 15, 'leadTimeDays' => 7],
            ['name' => 'Nismo Performance Exhaust', 'currentInventory' => 10, 'avgSalesPerWeek' => 5, 'leadTimeDays' => 15],
            ['name' => 'Garmin BC 40 Wireless Backup Camera', 'currentInventory' => 30, 'avgSalesPerWeek' => 10, 'leadTimeDays' => 6],
            ['name' => 'WeatherTech TechLiner Cargo Liner', 'currentInventory' => 80, 'avgSalesPerWeek' => 28, 'leadTimeDays' => 3],
            ['name' => 'MagnaFlow Performance Cat-Back Exhaust', 'currentInventory' => 18, 'avgSalesPerWeek' => 7, 'leadTimeDays' => 12],
            ['name' => 'Sony XAV-AX1000 Car Audio System', 'currentInventory' => 30, 'avgSalesPerWeek' => 12, 'leadTimeDays' => 7],
            ['name' => 'Mobil 1 Extended Performance Oil Filter', 'currentInventory' => 110, 'avgSalesPerWeek' => 35, 'leadTimeDays' => 3],
            ['name' => 'JVC KW-V250BT Receiver', 'currentInventory' => 35, 'avgSalesPerWeek' => 8, 'leadTimeDays' => 6],
            ['name' => 'Eibach Pro-Kit Performance Springs', 'currentInventory' => 15, 'avgSalesPerWeek' => 6, 'leadTimeDays' => 10],
            ['name' => 'Sparco Racing Steering Wheel', 'currentInventory' => 10, 'avgSalesPerWeek' => 4, 'leadTimeDays' => 15],
            ['name' => 'Cobra Electronics RAD450 Radar Detector', 'currentInventory' => 45, 'avgSalesPerWeek' => 15, 'leadTimeDays' => 6],
            ['name' => 'Nolan N87 Helmet', 'currentInventory' => 20, 'avgSalesPerWeek' => 6, 'leadTimeDays' => 12],
            ['name' => 'Pioneer TS-A1670F 6.5" Speakers', 'currentInventory' => 65, 'avgSalesPerWeek' => 22, 'leadTimeDays' => 4],
            ['name' => 'Motul Synthetic Blend Motor Oil 5W-30', 'currentInventory' => 85, 'avgSalesPerWeek' => 30, 'leadTimeDays' => 2],
            ['name' => 'THULE Rapid Podium Foot Pack', 'currentInventory' => 20, 'avgSalesPerWeek' => 8, 'leadTimeDays' => 9],
            ['name' => 'DashCam BlackVue DR900S-2CH', 'currentInventory' => 30, 'avgSalesPerWeek' => 10, 'leadTimeDays' => 7],
            ['name' => 'Nokian Hakkapeliitta R3 Winter Tire', 'currentInventory' => 40, 'avgSalesPerWeek' => 5, 'leadTimeDays' => 7],
            ['name' => 'Michelin Defender LTX M/S Tire', 'currentInventory' => 55, 'avgSalesPerWeek' => 11, 'leadTimeDays' => 6],
            ['name' => 'Alpine SPR-60C 6.5" Speakers', 'currentInventory' => 45, 'avgSalesPerWeek' => 15, 'leadTimeDays' => 7],
            ['name' => 'Sparco R100 Racing Seat', 'currentInventory' => 12, 'avgSalesPerWeek' => 4, 'leadTimeDays' => 15],
            ['name' => 'Shiftworks Short Shifter Kit', 'currentInventory' => 25, 'avgSalesPerWeek' => 9, 'leadTimeDays' => 8],
            ['name' => 'MSRP Rotors Brake Discs', 'currentInventory' => 30, 'avgSalesPerWeek' => 5, 'leadTimeDays' => 7],
            ['name' => 'Thule Motion XT Rooftop Cargo Box', 'currentInventory' => 18, 'avgSalesPerWeek' => 2, 'leadTimeDays' => 6],
            ['name' => 'Hella 500 LED Fog Light', 'currentInventory' => 20, 'avgSalesPerWeek' => 8, 'leadTimeDays' => 4],
            ['name' => 'Mobil 1 Motor Oil 0W-40', 'currentInventory' => 167, 'avgSalesPerWeek' => 23, 'leadTimeDays' => 5],
            ['name' => 'Falken Ziex ZE950 A/S Tire', 'currentInventory' => 30, 'avgSalesPerWeek' => 2, 'leadTimeDays' => 7],
            ['name' => 'MagnaFlow Performance Muffler', 'currentInventory' => 15, 'avgSalesPerWeek' => 5, 'leadTimeDays' => 11],
            ['name' => 'Kenda Klever A/T 2 Tires', 'currentInventory' => 40, 'avgSalesPerWeek' => 15, 'leadTimeDays' => 6],
            ['name' => 'Pioneer MVH-1400NEX Multimedia Receiver', 'currentInventory' => 17, 'avgSalesPerWeek' => 1, 'leadTimeDays' => 5]
        ];

        Product::insert($products);
    }
}